<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <Reference Include="System.Net.Http" />
    <ProjectReference Include="../../CADShark.OpenManage.Client.csproj" />
  </ItemGroup>
</Project>
